/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LWM2M_LWM2M_PB_H_INCLUDED
#define PB_LWM2M_LWM2M_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lwm2m_LwM2MBootstrapResultCode {
    lwm2m_LwM2MBootstrapResultCode_UNSPECIFIED = 0,
    lwm2m_LwM2MBootstrapResultCode_SUCCESS = 1,
    lwm2m_LwM2MBootstrapResultCode_INVALID_SIGNATURE = 2,
    lwm2m_LwM2MBootstrapResultCode_INVALID_MODEL = 3,
    lwm2m_LwM2MBootstrapResultCode_INVALID_SERIAL = 4,
    lwm2m_LwM2MBootstrapResultCode_OTHER_ERROR = 5,
    lwm2m_LwM2MBootstrapResultCode_DELETED = 6,
    lwm2m_LwM2MBootstrapResultCode_BANNED = 7
} lwm2m_LwM2MBootstrapResultCode;

/* Struct definitions */
/* around 40 bytes when serialized */
typedef struct _lwm2m_LwM2MAppearance {
    int32_t model;
    uint32_t serial;
} lwm2m_LwM2MAppearance;

typedef struct _lwm2m_LwM2MMessage {
    uint64_t timestamp; /* Server receive or client sample time */
    pb_size_t which_body;
    union {
        lwm2m_LwM2MAppearance appearance;
        /* Future message types here */
        pb_callback_t encrypted_data; /* inside is encrypted protobuf message */
    } body;
} lwm2m_LwM2MMessage;

typedef PB_BYTES_ARRAY_T(64) lwm2m_LwM2MDevice_public_key_t;
typedef struct _lwm2m_LwM2MDevice {
    int32_t model;
    uint32_t serial; /* also same meaning for node_id in mesh network */
    lwm2m_LwM2MDevice_public_key_t public_key; /* client public key */
    pb_byte_t aes_key[32]; /* symmetric key for AES-256-GCM */
} lwm2m_LwM2MDevice;

typedef struct _lwm2m_LwM2MDeviceMap {
    pb_callback_t devices;
} lwm2m_LwM2MDeviceMap;

typedef struct _lwm2m_LwM2MDeviceMap_DevicesEntry {
    uint32_t key;
    bool has_value;
    lwm2m_LwM2MDevice value;
} lwm2m_LwM2MDeviceMap_DevicesEntry;

typedef PB_BYTES_ARRAY_T(64) lwm2m_LwM2MDeviceChallenge_server_public_key_t;
/* when send challenge to device, will get raw encrypted bytes back */
typedef struct _lwm2m_LwM2MDeviceChallenge {
    uint32_t nounce; /* random transaction id generated by server */
    lwm2m_LwM2MDeviceChallenge_server_public_key_t server_public_key; /* presigned signature using trusted private key, and encrypted using ECDH + ChaCha20-Poly1305 */
} lwm2m_LwM2MDeviceChallenge;

/* send the request together with gateway PSK as security Guarantee */
typedef struct _lwm2m_LwM2MDeviceBootstrapRequest {
    uint32_t model;
    uint32_t serial;
    uint32_t nounce; /* random transaction id generated by server */
    pb_callback_t encrypted_data; /* basically test the encryption method between client and server */
} lwm2m_LwM2MDeviceBootstrapRequest;

typedef PB_BYTES_ARRAY_T(512) lwm2m_LwM2MBootstrapResponse_payload_t;
typedef struct _lwm2m_LwM2MBootstrapResponse {
    lwm2m_LwM2MBootstrapResultCode code;
    uint32_t nounce; /* the same nounce as in request */
    lwm2m_LwM2MBootstrapResponse_payload_t payload; /* presigned signature using trusted private key, and encrypted using ECDH + ChaCha20-Poly1305, the payload is serialized LwM2MDeviceBootstrap, only send this part to device */
} lwm2m_LwM2MBootstrapResponse;

typedef struct _lwm2m_LwM2MDeviceBootstrap {
    uint32_t pin; /* must be the same as on the device */
    uint32_t instance_id; /* unique per cluster */
    pb_callback_t admin_key; /* per device admin key */
    pb_callback_t aes_key; /* advertise data will be encrypted using this key */
} lwm2m_LwM2MDeviceBootstrap;

typedef PB_BYTES_ARRAY_T(256) lwm2m_LwM2MResourceGet_bytes_value_t;
typedef struct _lwm2m_LwM2MResourceGet {
    int32_t object_id;
    int32_t resource_id;
    int32_t resource_instance_id;
    pb_size_t which_value;
    union {
        lwm2m_LwM2MResourceGet_bytes_value_t bytes_value;
        char string_value[128];
        int32_t int_value;
        bool bool_value;
        float float_value;
        double double_value;
    } value;
} lwm2m_LwM2MResourceGet;

typedef PB_BYTES_ARRAY_T(256) lwm2m_LwM2MResourceSet_bytes_value_t;
typedef struct _lwm2m_LwM2MResourceSet {
    int32_t object_id;
    int32_t resource_id;
    int32_t resource_instance_id;
    pb_size_t which_value;
    union {
        lwm2m_LwM2MResourceSet_bytes_value_t bytes_value;
        char string_value[128];
        int32_t int_value;
        bool bool_value;
        float float_value;
        double double_value;
    } value;
} lwm2m_LwM2MResourceSet;

typedef PB_BYTES_ARRAY_T(32) lwm2m_FactoryPartition_public_key_t;
typedef PB_BYTES_ARRAY_T(32) lwm2m_FactoryPartition_private_key_t;
typedef PB_BYTES_ARRAY_T(128) lwm2m_FactoryPartition_bootstrap_server_t;
typedef PB_BYTES_ARRAY_T(64) lwm2m_FactoryPartition_signature_t;
typedef struct _lwm2m_FactoryPartition {
    char serial[16];
    int32_t pin; /* pin code for provisioning */
    lwm2m_FactoryPartition_public_key_t public_key; /* client public key */
    lwm2m_FactoryPartition_private_key_t private_key; /* client private key */
    lwm2m_FactoryPartition_bootstrap_server_t bootstrap_server; /* bootstrap server URL */
    lwm2m_FactoryPartition_signature_t signature; /* signature of the above fields using factory private key */
    pb_callback_t signature_cert; /* certificate of the factory public key */
} lwm2m_FactoryPartition;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lwm2m_LwM2MBootstrapResultCode_MIN lwm2m_LwM2MBootstrapResultCode_UNSPECIFIED
#define _lwm2m_LwM2MBootstrapResultCode_MAX lwm2m_LwM2MBootstrapResultCode_BANNED
#define _lwm2m_LwM2MBootstrapResultCode_ARRAYSIZE ((lwm2m_LwM2MBootstrapResultCode)(lwm2m_LwM2MBootstrapResultCode_BANNED+1))








#define lwm2m_LwM2MBootstrapResponse_code_ENUMTYPE lwm2m_LwM2MBootstrapResultCode






/* Initializer values for message structs */
#define lwm2m_LwM2MMessage_init_default          {0, 0, {lwm2m_LwM2MAppearance_init_default}}
#define lwm2m_LwM2MAppearance_init_default       {0, 0}
#define lwm2m_LwM2MDevice_init_default           {0, 0, {0, {0}}, {0}}
#define lwm2m_LwM2MDeviceMap_init_default        {{{NULL}, NULL}}
#define lwm2m_LwM2MDeviceMap_DevicesEntry_init_default {0, false, lwm2m_LwM2MDevice_init_default}
#define lwm2m_LwM2MDeviceChallenge_init_default  {0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrapRequest_init_default {0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MBootstrapResponse_init_default {_lwm2m_LwM2MBootstrapResultCode_MIN, 0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrap_init_default  {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_LwM2MResourceGet_init_default      {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_LwM2MResourceSet_init_default      {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_FactoryPartition_init_default      {"", 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {{NULL}, NULL}}
#define lwm2m_LwM2MMessage_init_zero             {0, 0, {lwm2m_LwM2MAppearance_init_zero}}
#define lwm2m_LwM2MAppearance_init_zero          {0, 0}
#define lwm2m_LwM2MDevice_init_zero              {0, 0, {0, {0}}, {0}}
#define lwm2m_LwM2MDeviceMap_init_zero           {{{NULL}, NULL}}
#define lwm2m_LwM2MDeviceMap_DevicesEntry_init_zero {0, false, lwm2m_LwM2MDevice_init_zero}
#define lwm2m_LwM2MDeviceChallenge_init_zero     {0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrapRequest_init_zero {0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MBootstrapResponse_init_zero   {_lwm2m_LwM2MBootstrapResultCode_MIN, 0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrap_init_zero     {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_LwM2MResourceGet_init_zero         {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_LwM2MResourceSet_init_zero         {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_FactoryPartition_init_zero         {"", 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define lwm2m_LwM2MAppearance_model_tag          1
#define lwm2m_LwM2MAppearance_serial_tag         2
#define lwm2m_LwM2MMessage_timestamp_tag         1
#define lwm2m_LwM2MMessage_appearance_tag        100
#define lwm2m_LwM2MMessage_encrypted_data_tag    101
#define lwm2m_LwM2MDevice_model_tag              1
#define lwm2m_LwM2MDevice_serial_tag             2
#define lwm2m_LwM2MDevice_public_key_tag         3
#define lwm2m_LwM2MDevice_aes_key_tag            4
#define lwm2m_LwM2MDeviceMap_devices_tag         1
#define lwm2m_LwM2MDeviceMap_DevicesEntry_key_tag 1
#define lwm2m_LwM2MDeviceMap_DevicesEntry_value_tag 2
#define lwm2m_LwM2MDeviceChallenge_nounce_tag    1
#define lwm2m_LwM2MDeviceChallenge_server_public_key_tag 2
#define lwm2m_LwM2MDeviceBootstrapRequest_model_tag 1
#define lwm2m_LwM2MDeviceBootstrapRequest_serial_tag 2
#define lwm2m_LwM2MDeviceBootstrapRequest_nounce_tag 3
#define lwm2m_LwM2MDeviceBootstrapRequest_encrypted_data_tag 4
#define lwm2m_LwM2MBootstrapResponse_code_tag    1
#define lwm2m_LwM2MBootstrapResponse_nounce_tag  2
#define lwm2m_LwM2MBootstrapResponse_payload_tag 3
#define lwm2m_LwM2MDeviceBootstrap_pin_tag       1
#define lwm2m_LwM2MDeviceBootstrap_instance_id_tag 2
#define lwm2m_LwM2MDeviceBootstrap_admin_key_tag 3
#define lwm2m_LwM2MDeviceBootstrap_aes_key_tag   4
#define lwm2m_LwM2MResourceGet_object_id_tag     1
#define lwm2m_LwM2MResourceGet_resource_id_tag   2
#define lwm2m_LwM2MResourceGet_resource_instance_id_tag 3
#define lwm2m_LwM2MResourceGet_bytes_value_tag   4
#define lwm2m_LwM2MResourceGet_string_value_tag  5
#define lwm2m_LwM2MResourceGet_int_value_tag     6
#define lwm2m_LwM2MResourceGet_bool_value_tag    7
#define lwm2m_LwM2MResourceGet_float_value_tag   8
#define lwm2m_LwM2MResourceGet_double_value_tag  9
#define lwm2m_LwM2MResourceSet_object_id_tag     1
#define lwm2m_LwM2MResourceSet_resource_id_tag   2
#define lwm2m_LwM2MResourceSet_resource_instance_id_tag 3
#define lwm2m_LwM2MResourceSet_bytes_value_tag   4
#define lwm2m_LwM2MResourceSet_string_value_tag  5
#define lwm2m_LwM2MResourceSet_int_value_tag     6
#define lwm2m_LwM2MResourceSet_bool_value_tag    7
#define lwm2m_LwM2MResourceSet_float_value_tag   8
#define lwm2m_LwM2MResourceSet_double_value_tag  9
#define lwm2m_FactoryPartition_serial_tag        1
#define lwm2m_FactoryPartition_pin_tag           2
#define lwm2m_FactoryPartition_public_key_tag    3
#define lwm2m_FactoryPartition_private_key_tag   4
#define lwm2m_FactoryPartition_bootstrap_server_tag 5
#define lwm2m_FactoryPartition_signature_tag     6
#define lwm2m_FactoryPartition_signature_cert_tag 7

/* Struct field encoding specification for nanopb */
#define lwm2m_LwM2MMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,appearance,body.appearance), 100) \
X(a, CALLBACK, ONEOF,    BYTES,    (body,encrypted_data,body.encrypted_data), 101)
#define lwm2m_LwM2MMessage_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MMessage_DEFAULT NULL
#define lwm2m_LwM2MMessage_body_appearance_MSGTYPE lwm2m_LwM2MAppearance

#define lwm2m_LwM2MAppearance_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2)
#define lwm2m_LwM2MAppearance_CALLBACK NULL
#define lwm2m_LwM2MAppearance_DEFAULT NULL

#define lwm2m_LwM2MDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, aes_key,           4)
#define lwm2m_LwM2MDevice_CALLBACK NULL
#define lwm2m_LwM2MDevice_DEFAULT NULL

#define lwm2m_LwM2MDeviceMap_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  devices,           1)
#define lwm2m_LwM2MDeviceMap_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceMap_DEFAULT NULL
#define lwm2m_LwM2MDeviceMap_devices_MSGTYPE lwm2m_LwM2MDeviceMap_DevicesEntry

#define lwm2m_LwM2MDeviceMap_DevicesEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define lwm2m_LwM2MDeviceMap_DevicesEntry_CALLBACK NULL
#define lwm2m_LwM2MDeviceMap_DevicesEntry_DEFAULT NULL
#define lwm2m_LwM2MDeviceMap_DevicesEntry_value_MSGTYPE lwm2m_LwM2MDevice

#define lwm2m_LwM2MDeviceChallenge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            1) \
X(a, STATIC,   SINGULAR, BYTES,    server_public_key,   2)
#define lwm2m_LwM2MDeviceChallenge_CALLBACK NULL
#define lwm2m_LwM2MDeviceChallenge_DEFAULT NULL

#define lwm2m_LwM2MDeviceBootstrapRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            3) \
X(a, CALLBACK, SINGULAR, BYTES,    encrypted_data,    4)
#define lwm2m_LwM2MDeviceBootstrapRequest_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceBootstrapRequest_DEFAULT NULL

#define lwm2m_LwM2MBootstrapResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            2) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           3)
#define lwm2m_LwM2MBootstrapResponse_CALLBACK NULL
#define lwm2m_LwM2MBootstrapResponse_DEFAULT NULL

#define lwm2m_LwM2MDeviceBootstrap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               1) \
X(a, STATIC,   SINGULAR, UINT32,   instance_id,       2) \
X(a, CALLBACK, SINGULAR, BYTES,    admin_key,         3) \
X(a, CALLBACK, SINGULAR, BYTES,    aes_key,           4)
#define lwm2m_LwM2MDeviceBootstrap_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceBootstrap_DEFAULT NULL

#define lwm2m_LwM2MResourceGet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   object_id,         1) \
X(a, STATIC,   SINGULAR, SINT32,   resource_id,       2) \
X(a, STATIC,   SINGULAR, SINT32,   resource_instance_id,   3) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),   4) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   7) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   8) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   9)
#define lwm2m_LwM2MResourceGet_CALLBACK NULL
#define lwm2m_LwM2MResourceGet_DEFAULT NULL

#define lwm2m_LwM2MResourceSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   object_id,         1) \
X(a, STATIC,   SINGULAR, SINT32,   resource_id,       2) \
X(a, STATIC,   SINGULAR, SINT32,   resource_instance_id,   3) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),   4) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   7) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   8) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   9)
#define lwm2m_LwM2MResourceSet_CALLBACK NULL
#define lwm2m_LwM2MResourceSet_DEFAULT NULL

#define lwm2m_FactoryPartition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   serial,            1) \
X(a, STATIC,   SINGULAR, SINT32,   pin,               2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, BYTES,    private_key,       4) \
X(a, STATIC,   SINGULAR, BYTES,    bootstrap_server,   5) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         6) \
X(a, CALLBACK, SINGULAR, BYTES,    signature_cert,    7)
#define lwm2m_FactoryPartition_CALLBACK pb_default_field_callback
#define lwm2m_FactoryPartition_DEFAULT NULL

extern const pb_msgdesc_t lwm2m_LwM2MMessage_msg;
extern const pb_msgdesc_t lwm2m_LwM2MAppearance_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDevice_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceMap_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceMap_DevicesEntry_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceChallenge_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceBootstrapRequest_msg;
extern const pb_msgdesc_t lwm2m_LwM2MBootstrapResponse_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceBootstrap_msg;
extern const pb_msgdesc_t lwm2m_LwM2MResourceGet_msg;
extern const pb_msgdesc_t lwm2m_LwM2MResourceSet_msg;
extern const pb_msgdesc_t lwm2m_FactoryPartition_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lwm2m_LwM2MMessage_fields &lwm2m_LwM2MMessage_msg
#define lwm2m_LwM2MAppearance_fields &lwm2m_LwM2MAppearance_msg
#define lwm2m_LwM2MDevice_fields &lwm2m_LwM2MDevice_msg
#define lwm2m_LwM2MDeviceMap_fields &lwm2m_LwM2MDeviceMap_msg
#define lwm2m_LwM2MDeviceMap_DevicesEntry_fields &lwm2m_LwM2MDeviceMap_DevicesEntry_msg
#define lwm2m_LwM2MDeviceChallenge_fields &lwm2m_LwM2MDeviceChallenge_msg
#define lwm2m_LwM2MDeviceBootstrapRequest_fields &lwm2m_LwM2MDeviceBootstrapRequest_msg
#define lwm2m_LwM2MBootstrapResponse_fields &lwm2m_LwM2MBootstrapResponse_msg
#define lwm2m_LwM2MDeviceBootstrap_fields &lwm2m_LwM2MDeviceBootstrap_msg
#define lwm2m_LwM2MResourceGet_fields &lwm2m_LwM2MResourceGet_msg
#define lwm2m_LwM2MResourceSet_fields &lwm2m_LwM2MResourceSet_msg
#define lwm2m_FactoryPartition_fields &lwm2m_FactoryPartition_msg

/* Maximum encoded size of messages (where known) */
/* lwm2m_LwM2MMessage_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceMap_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceBootstrapRequest_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceBootstrap_size depends on runtime parameters */
/* lwm2m_FactoryPartition_size depends on runtime parameters */
#define LWM2M_LWM2M_PB_H_MAX_SIZE                lwm2m_LwM2MBootstrapResponse_size
#define lwm2m_LwM2MAppearance_size               12
#define lwm2m_LwM2MBootstrapResponse_size        523
#define lwm2m_LwM2MDeviceChallenge_size          72
#define lwm2m_LwM2MDeviceMap_DevicesEntry_size   120
#define lwm2m_LwM2MDevice_size                   112
#define lwm2m_LwM2MResourceGet_size              277
#define lwm2m_LwM2MResourceSet_size              277

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
