/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LWM2M_LWM2M_PB_H_INCLUDED
#define PB_LWM2M_LWM2M_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _lwm2m_ConnectionType {
    lwm2m_ConnectionType_CONNECTION_WIFI = 0,
    lwm2m_ConnectionType_CONNECTION_BLE = 1,
    lwm2m_ConnectionType_CONNECTION_LORA = 2,
    lwm2m_ConnectionType_CONNECTION_RS485 = 3
} lwm2m_ConnectionType;

typedef enum _lwm2m_LwM2MBootstrapResultCode {
    lwm2m_LwM2MBootstrapResultCode_UNSPECIFIED = 0,
    lwm2m_LwM2MBootstrapResultCode_SUCCESS = 1,
    lwm2m_LwM2MBootstrapResultCode_INVALID_SIGNATURE = 2,
    lwm2m_LwM2MBootstrapResultCode_INVALID_MODEL = 3,
    lwm2m_LwM2MBootstrapResultCode_INVALID_SERIAL = 4,
    lwm2m_LwM2MBootstrapResultCode_OTHER_ERROR = 5,
    lwm2m_LwM2MBootstrapResultCode_DELETED = 6,
    lwm2m_LwM2MBootstrapResultCode_BANNED = 7
} lwm2m_LwM2MBootstrapResultCode;

/* Struct definitions */
typedef struct _lwm2m_LwM2MCommand {
    pb_size_t which_body;
    union {
        /* Future message types here */
        bool reset; /* inside is encrypted protobuf message */
        bool reboot; /* inside is encrypted protobuf message */
    } body;
} lwm2m_LwM2MCommand;

typedef struct _lwm2m_LwM2MStatusReport {
    int32_t battery_level;
    int32_t uptime;
    int32_t things_type;
    int32_t things_id;
    int32_t things_feature; /* array index in the things type */
    pb_callback_t data; /* key is object id (high 16 bits) + resource id (low 16 bits) */
} lwm2m_LwM2MStatusReport;

typedef struct _lwm2m_LwM2MSensorValue {
    pb_size_t which_value;
    union {
        pb_callback_t bytes_value;
        pb_callback_t string_value;
        int32_t int_value;
        bool bool_value;
        float float_value;
        double double_value;
    } value;
} lwm2m_LwM2MSensorValue;

typedef struct _lwm2m_LwM2MStatusReport_DataEntry {
    uint32_t key;
    bool has_value;
    lwm2m_LwM2MSensorValue value;
} lwm2m_LwM2MStatusReport_DataEntry;

typedef PB_BYTES_ARRAY_T(64) lwm2m_LwM2MDevice_public_key_t;
typedef struct _lwm2m_LwM2MDevice {
    int32_t model;
    uint32_t serial; /* also same meaning for node_id in mesh network */
    lwm2m_LwM2MDevice_public_key_t public_key; /* client public key */
    pb_byte_t aes_key[32]; /* symmetric key for AES-256-GCM */
    pb_callback_t mac_address;
    int32_t instance_id; /* unique per cluster */
    bool banned; /* if true, device is banned and cannot connect */
    lwm2m_ConnectionType connection_type; /* Connection type enum */
} lwm2m_LwM2MDevice;

typedef struct _lwm2m_LwM2MDeviceMap {
    pb_callback_t devices;
} lwm2m_LwM2MDeviceMap;

typedef struct _lwm2m_LwM2MDeviceMap_DevicesEntry {
    uint32_t key;
    bool has_value;
    lwm2m_LwM2MDevice value;
} lwm2m_LwM2MDeviceMap_DevicesEntry;

typedef PB_BYTES_ARRAY_T(32) lwm2m_LwM2MDeviceChallenge_public_key_t;
/* when send challenge to device, will get raw encrypted bytes back */
typedef struct _lwm2m_LwM2MDeviceChallenge {
    uint32_t nounce; /* random transaction id generated by server */
    lwm2m_LwM2MDeviceChallenge_public_key_t public_key; /* presigned signature using trusted private key, and encrypted using ECDH + ChaCha20-Poly1305 */
} lwm2m_LwM2MDeviceChallenge;

typedef PB_BYTES_ARRAY_T(32) lwm2m_LwM2MDeviceChallengeAnswer_public_key_t;
typedef PB_BYTES_ARRAY_T(128) lwm2m_LwM2MDeviceChallengeAnswer_signature_t;
typedef struct _lwm2m_LwM2MDeviceChallengeAnswer {
    lwm2m_LwM2MDeviceChallengeAnswer_public_key_t public_key; /* presigned signature using trusted private key, and encrypted using ECDH + ChaCha20-Poly1305 */
    lwm2m_LwM2MDeviceChallengeAnswer_signature_t signature; /* signature of the above fields using device private key */
} lwm2m_LwM2MDeviceChallengeAnswer;

typedef struct _lwm2m_LwM2MMessage {
    int32_t model;
    uint32_t serial; /* also same meaning for node_id in mesh network */
    pb_size_t which_body;
    union {
        /* Future message types here */
        pb_callback_t encrypted_data; /* inside is encrypted protobuf message */
        lwm2m_LwM2MCommand command;
        lwm2m_LwM2MStatusReport status_report;
        lwm2m_LwM2MDeviceChallenge device_challenge;
        lwm2m_LwM2MDeviceChallengeAnswer device_challenge_answer;
    } body;
} lwm2m_LwM2MMessage;

/* send the request together with gateway PSK as security Guarantee */
typedef struct _lwm2m_LwM2MDeviceBootstrapRequest {
    uint32_t model;
    uint32_t serial;
    uint32_t nounce; /* random transaction id generated by server */
    pb_callback_t encrypted_data; /* basically test the encryption method between client and server */
} lwm2m_LwM2MDeviceBootstrapRequest;

typedef PB_BYTES_ARRAY_T(512) lwm2m_LwM2MBootstrapResponse_payload_t;
typedef struct _lwm2m_LwM2MBootstrapResponse {
    lwm2m_LwM2MBootstrapResultCode code;
    uint32_t nounce; /* the same nounce as in request */
    lwm2m_LwM2MBootstrapResponse_payload_t payload; /* presigned signature using trusted private key, and encrypted using ECDH + ChaCha20-Poly1305, the payload is serialized LwM2MDeviceBootstrap, only send this part to device */
} lwm2m_LwM2MBootstrapResponse;

typedef struct _lwm2m_LwM2MDeviceBootstrap {
    uint32_t pin; /* must be the same as on the device */
    uint32_t instance_id; /* unique per cluster */
    pb_callback_t admin_key; /* per device admin key */
    pb_callback_t aes_key; /* advertise data will be encrypted using this key */
} lwm2m_LwM2MDeviceBootstrap;

typedef PB_BYTES_ARRAY_T(256) lwm2m_LwM2MResourceGet_bytes_value_t;
typedef struct _lwm2m_LwM2MResourceGet {
    int32_t object_id;
    int32_t resource_id;
    int32_t resource_instance_id;
    pb_size_t which_value;
    union {
        lwm2m_LwM2MResourceGet_bytes_value_t bytes_value;
        char string_value[128];
        int32_t int_value;
        bool bool_value;
        float float_value;
        double double_value;
    } value;
} lwm2m_LwM2MResourceGet;

typedef PB_BYTES_ARRAY_T(256) lwm2m_LwM2MResourceSet_bytes_value_t;
typedef struct _lwm2m_LwM2MResourceSet {
    int32_t object_id;
    int32_t resource_id;
    int32_t resource_instance_id;
    pb_size_t which_value;
    union {
        lwm2m_LwM2MResourceSet_bytes_value_t bytes_value;
        char string_value[128];
        int32_t int_value;
        bool bool_value;
        float float_value;
        double double_value;
    } value;
} lwm2m_LwM2MResourceSet;

typedef PB_BYTES_ARRAY_T(32) lwm2m_FactoryPartition_public_key_t;
typedef PB_BYTES_ARRAY_T(32) lwm2m_FactoryPartition_private_key_t;
typedef PB_BYTES_ARRAY_T(128) lwm2m_FactoryPartition_bootstrap_server_t;
typedef PB_BYTES_ARRAY_T(64) lwm2m_FactoryPartition_signature_t;
typedef PB_BYTES_ARRAY_T(32) lwm2m_FactoryPartition_signature_cert_t;
typedef struct _lwm2m_FactoryPartition {
    char serial[16];
    int32_t pin; /* pin code for provisioning */
    lwm2m_FactoryPartition_public_key_t public_key; /* client public key */
    lwm2m_FactoryPartition_private_key_t private_key; /* client private key */
    lwm2m_FactoryPartition_bootstrap_server_t bootstrap_server; /* bootstrap server URL */
    lwm2m_FactoryPartition_signature_t signature; /* signature of the above fields using factory private key */
    lwm2m_FactoryPartition_signature_cert_t signature_cert; /* certificate of the factory public key */
    int32_t model; /* device model */
    uint32_t serial_number; /* device serial number */
} lwm2m_FactoryPartition;

typedef struct _lwm2m_Things {
    int32_t type;
    int32_t id;
    pb_callback_t features;
} lwm2m_Things;

typedef struct _lwm2m_ThingsFeature {
    int32_t id;
    pb_callback_t data;
} lwm2m_ThingsFeature;

typedef struct _lwm2m_ThingsFeature_DataEntry {
    uint32_t key;
    bool has_value;
    lwm2m_LwM2MSensorValue value;
} lwm2m_ThingsFeature_DataEntry;

typedef struct _lwm2m_ThingsTemplate {
    int32_t type;
    pb_callback_t features;
} lwm2m_ThingsTemplate;

typedef struct _lwm2m_ThingsTemplateFeature {
    int32_t id;
    pb_callback_t fields;
} lwm2m_ThingsTemplateFeature;

typedef struct _lwm2m_ThingsTemplateField {
    int32_t id;
    pb_callback_t name;
    pb_callback_t type;
} lwm2m_ThingsTemplateField;

typedef struct _lwm2m_ThingsTemplateAction {
    int32_t type;
    int32_t id;
    int32_t feature_id;
} lwm2m_ThingsTemplateAction;

typedef struct _lwm2m_ThingsTemplateEvent {
    int32_t id;
    pb_callback_t name;
} lwm2m_ThingsTemplateEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _lwm2m_ConnectionType_MIN lwm2m_ConnectionType_CONNECTION_WIFI
#define _lwm2m_ConnectionType_MAX lwm2m_ConnectionType_CONNECTION_RS485
#define _lwm2m_ConnectionType_ARRAYSIZE ((lwm2m_ConnectionType)(lwm2m_ConnectionType_CONNECTION_RS485+1))

#define _lwm2m_LwM2MBootstrapResultCode_MIN lwm2m_LwM2MBootstrapResultCode_UNSPECIFIED
#define _lwm2m_LwM2MBootstrapResultCode_MAX lwm2m_LwM2MBootstrapResultCode_BANNED
#define _lwm2m_LwM2MBootstrapResultCode_ARRAYSIZE ((lwm2m_LwM2MBootstrapResultCode)(lwm2m_LwM2MBootstrapResultCode_BANNED+1))






#define lwm2m_LwM2MDevice_connection_type_ENUMTYPE lwm2m_ConnectionType






#define lwm2m_LwM2MBootstrapResponse_code_ENUMTYPE lwm2m_LwM2MBootstrapResultCode














/* Initializer values for message structs */
#define lwm2m_LwM2MMessage_init_default          {0, 0, 0, {{{NULL}, NULL}}}
#define lwm2m_LwM2MCommand_init_default          {0, {0}}
#define lwm2m_LwM2MStatusReport_init_default     {0, 0, 0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MStatusReport_DataEntry_init_default {0, false, lwm2m_LwM2MSensorValue_init_default}
#define lwm2m_LwM2MSensorValue_init_default      {0, {{{NULL}, NULL}}}
#define lwm2m_LwM2MDevice_init_default           {0, 0, {0, {0}}, {0}, {{NULL}, NULL}, 0, 0, _lwm2m_ConnectionType_MIN}
#define lwm2m_LwM2MDeviceMap_init_default        {{{NULL}, NULL}}
#define lwm2m_LwM2MDeviceMap_DevicesEntry_init_default {0, false, lwm2m_LwM2MDevice_init_default}
#define lwm2m_LwM2MDeviceChallenge_init_default  {0, {0, {0}}}
#define lwm2m_LwM2MDeviceChallengeAnswer_init_default {{0, {0}}, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrapRequest_init_default {0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MBootstrapResponse_init_default {_lwm2m_LwM2MBootstrapResultCode_MIN, 0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrap_init_default  {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_LwM2MResourceGet_init_default      {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_LwM2MResourceSet_init_default      {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_FactoryPartition_init_default      {"", 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, 0}
#define lwm2m_Things_init_default                {0, 0, {{NULL}, NULL}}
#define lwm2m_ThingsFeature_init_default         {0, {{NULL}, NULL}}
#define lwm2m_ThingsFeature_DataEntry_init_default {0, false, lwm2m_LwM2MSensorValue_init_default}
#define lwm2m_ThingsTemplate_init_default        {0, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateFeature_init_default {0, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateField_init_default   {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateAction_init_default  {0, 0, 0}
#define lwm2m_ThingsTemplateEvent_init_default   {0, {{NULL}, NULL}}
#define lwm2m_LwM2MMessage_init_zero             {0, 0, 0, {{{NULL}, NULL}}}
#define lwm2m_LwM2MCommand_init_zero             {0, {0}}
#define lwm2m_LwM2MStatusReport_init_zero        {0, 0, 0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MStatusReport_DataEntry_init_zero {0, false, lwm2m_LwM2MSensorValue_init_zero}
#define lwm2m_LwM2MSensorValue_init_zero         {0, {{{NULL}, NULL}}}
#define lwm2m_LwM2MDevice_init_zero              {0, 0, {0, {0}}, {0}, {{NULL}, NULL}, 0, 0, _lwm2m_ConnectionType_MIN}
#define lwm2m_LwM2MDeviceMap_init_zero           {{{NULL}, NULL}}
#define lwm2m_LwM2MDeviceMap_DevicesEntry_init_zero {0, false, lwm2m_LwM2MDevice_init_zero}
#define lwm2m_LwM2MDeviceChallenge_init_zero     {0, {0, {0}}}
#define lwm2m_LwM2MDeviceChallengeAnswer_init_zero {{0, {0}}, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrapRequest_init_zero {0, 0, 0, {{NULL}, NULL}}
#define lwm2m_LwM2MBootstrapResponse_init_zero   {_lwm2m_LwM2MBootstrapResultCode_MIN, 0, {0, {0}}}
#define lwm2m_LwM2MDeviceBootstrap_init_zero     {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_LwM2MResourceGet_init_zero         {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_LwM2MResourceSet_init_zero         {0, 0, 0, 0, {{0, {0}}}}
#define lwm2m_FactoryPartition_init_zero         {"", 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, 0, 0}
#define lwm2m_Things_init_zero                   {0, 0, {{NULL}, NULL}}
#define lwm2m_ThingsFeature_init_zero            {0, {{NULL}, NULL}}
#define lwm2m_ThingsFeature_DataEntry_init_zero  {0, false, lwm2m_LwM2MSensorValue_init_zero}
#define lwm2m_ThingsTemplate_init_zero           {0, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateFeature_init_zero    {0, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateField_init_zero      {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwm2m_ThingsTemplateAction_init_zero     {0, 0, 0}
#define lwm2m_ThingsTemplateEvent_init_zero      {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define lwm2m_LwM2MCommand_reset_tag             1
#define lwm2m_LwM2MCommand_reboot_tag            2
#define lwm2m_LwM2MStatusReport_battery_level_tag 1
#define lwm2m_LwM2MStatusReport_uptime_tag       2
#define lwm2m_LwM2MStatusReport_things_type_tag  3
#define lwm2m_LwM2MStatusReport_things_id_tag    4
#define lwm2m_LwM2MStatusReport_things_feature_tag 5
#define lwm2m_LwM2MStatusReport_data_tag         100
#define lwm2m_LwM2MSensorValue_bytes_value_tag   1
#define lwm2m_LwM2MSensorValue_string_value_tag  2
#define lwm2m_LwM2MSensorValue_int_value_tag     3
#define lwm2m_LwM2MSensorValue_bool_value_tag    4
#define lwm2m_LwM2MSensorValue_float_value_tag   5
#define lwm2m_LwM2MSensorValue_double_value_tag  6
#define lwm2m_LwM2MStatusReport_DataEntry_key_tag 1
#define lwm2m_LwM2MStatusReport_DataEntry_value_tag 2
#define lwm2m_LwM2MDevice_model_tag              1
#define lwm2m_LwM2MDevice_serial_tag             2
#define lwm2m_LwM2MDevice_public_key_tag         3
#define lwm2m_LwM2MDevice_aes_key_tag            4
#define lwm2m_LwM2MDevice_mac_address_tag        5
#define lwm2m_LwM2MDevice_instance_id_tag        6
#define lwm2m_LwM2MDevice_banned_tag             7
#define lwm2m_LwM2MDevice_connection_type_tag    8
#define lwm2m_LwM2MDeviceMap_devices_tag         1
#define lwm2m_LwM2MDeviceMap_DevicesEntry_key_tag 1
#define lwm2m_LwM2MDeviceMap_DevicesEntry_value_tag 2
#define lwm2m_LwM2MDeviceChallenge_nounce_tag    1
#define lwm2m_LwM2MDeviceChallenge_public_key_tag 2
#define lwm2m_LwM2MDeviceChallengeAnswer_public_key_tag 1
#define lwm2m_LwM2MDeviceChallengeAnswer_signature_tag 2
#define lwm2m_LwM2MMessage_model_tag             1
#define lwm2m_LwM2MMessage_serial_tag            2
#define lwm2m_LwM2MMessage_encrypted_data_tag    100
#define lwm2m_LwM2MMessage_command_tag           101
#define lwm2m_LwM2MMessage_status_report_tag     102
#define lwm2m_LwM2MMessage_device_challenge_tag  103
#define lwm2m_LwM2MMessage_device_challenge_answer_tag 104
#define lwm2m_LwM2MDeviceBootstrapRequest_model_tag 1
#define lwm2m_LwM2MDeviceBootstrapRequest_serial_tag 2
#define lwm2m_LwM2MDeviceBootstrapRequest_nounce_tag 3
#define lwm2m_LwM2MDeviceBootstrapRequest_encrypted_data_tag 4
#define lwm2m_LwM2MBootstrapResponse_code_tag    1
#define lwm2m_LwM2MBootstrapResponse_nounce_tag  2
#define lwm2m_LwM2MBootstrapResponse_payload_tag 3
#define lwm2m_LwM2MDeviceBootstrap_pin_tag       1
#define lwm2m_LwM2MDeviceBootstrap_instance_id_tag 2
#define lwm2m_LwM2MDeviceBootstrap_admin_key_tag 3
#define lwm2m_LwM2MDeviceBootstrap_aes_key_tag   4
#define lwm2m_LwM2MResourceGet_object_id_tag     1
#define lwm2m_LwM2MResourceGet_resource_id_tag   2
#define lwm2m_LwM2MResourceGet_resource_instance_id_tag 3
#define lwm2m_LwM2MResourceGet_bytes_value_tag   4
#define lwm2m_LwM2MResourceGet_string_value_tag  5
#define lwm2m_LwM2MResourceGet_int_value_tag     6
#define lwm2m_LwM2MResourceGet_bool_value_tag    7
#define lwm2m_LwM2MResourceGet_float_value_tag   8
#define lwm2m_LwM2MResourceGet_double_value_tag  9
#define lwm2m_LwM2MResourceSet_object_id_tag     1
#define lwm2m_LwM2MResourceSet_resource_id_tag   2
#define lwm2m_LwM2MResourceSet_resource_instance_id_tag 3
#define lwm2m_LwM2MResourceSet_bytes_value_tag   4
#define lwm2m_LwM2MResourceSet_string_value_tag  5
#define lwm2m_LwM2MResourceSet_int_value_tag     6
#define lwm2m_LwM2MResourceSet_bool_value_tag    7
#define lwm2m_LwM2MResourceSet_float_value_tag   8
#define lwm2m_LwM2MResourceSet_double_value_tag  9
#define lwm2m_FactoryPartition_serial_tag        1
#define lwm2m_FactoryPartition_pin_tag           2
#define lwm2m_FactoryPartition_public_key_tag    3
#define lwm2m_FactoryPartition_private_key_tag   4
#define lwm2m_FactoryPartition_bootstrap_server_tag 5
#define lwm2m_FactoryPartition_signature_tag     6
#define lwm2m_FactoryPartition_signature_cert_tag 7
#define lwm2m_FactoryPartition_model_tag         8
#define lwm2m_FactoryPartition_serial_number_tag 9
#define lwm2m_Things_type_tag                    1
#define lwm2m_Things_id_tag                      2
#define lwm2m_Things_features_tag                3
#define lwm2m_ThingsFeature_id_tag               1
#define lwm2m_ThingsFeature_data_tag             100
#define lwm2m_ThingsFeature_DataEntry_key_tag    1
#define lwm2m_ThingsFeature_DataEntry_value_tag  2
#define lwm2m_ThingsTemplate_type_tag            1
#define lwm2m_ThingsTemplate_features_tag        2
#define lwm2m_ThingsTemplateFeature_id_tag       1
#define lwm2m_ThingsTemplateFeature_fields_tag   2
#define lwm2m_ThingsTemplateField_id_tag         1
#define lwm2m_ThingsTemplateField_name_tag       2
#define lwm2m_ThingsTemplateField_type_tag       3
#define lwm2m_ThingsTemplateAction_type_tag      1
#define lwm2m_ThingsTemplateAction_id_tag        2
#define lwm2m_ThingsTemplateAction_feature_id_tag 3
#define lwm2m_ThingsTemplateEvent_id_tag         1
#define lwm2m_ThingsTemplateEvent_name_tag       2

/* Struct field encoding specification for nanopb */
#define lwm2m_LwM2MMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, CALLBACK, ONEOF,    BYTES,    (body,encrypted_data,body.encrypted_data), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,command,body.command), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,status_report,body.status_report), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,device_challenge,body.device_challenge), 103) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,device_challenge_answer,body.device_challenge_answer), 104)
#define lwm2m_LwM2MMessage_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MMessage_DEFAULT NULL
#define lwm2m_LwM2MMessage_body_command_MSGTYPE lwm2m_LwM2MCommand
#define lwm2m_LwM2MMessage_body_status_report_MSGTYPE lwm2m_LwM2MStatusReport
#define lwm2m_LwM2MMessage_body_device_challenge_MSGTYPE lwm2m_LwM2MDeviceChallenge
#define lwm2m_LwM2MMessage_body_device_challenge_answer_MSGTYPE lwm2m_LwM2MDeviceChallengeAnswer

#define lwm2m_LwM2MCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (body,reset,body.reset),   1) \
X(a, STATIC,   ONEOF,    BOOL,     (body,reboot,body.reboot),   2)
#define lwm2m_LwM2MCommand_CALLBACK NULL
#define lwm2m_LwM2MCommand_DEFAULT NULL

#define lwm2m_LwM2MStatusReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   battery_level,     1) \
X(a, STATIC,   SINGULAR, SINT32,   uptime,            2) \
X(a, STATIC,   SINGULAR, SINT32,   things_type,       3) \
X(a, STATIC,   SINGULAR, SINT32,   things_id,         4) \
X(a, STATIC,   SINGULAR, SINT32,   things_feature,    5) \
X(a, CALLBACK, REPEATED, MESSAGE,  data,            100)
#define lwm2m_LwM2MStatusReport_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MStatusReport_DEFAULT NULL
#define lwm2m_LwM2MStatusReport_data_MSGTYPE lwm2m_LwM2MStatusReport_DataEntry

#define lwm2m_LwM2MStatusReport_DataEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define lwm2m_LwM2MStatusReport_DataEntry_CALLBACK NULL
#define lwm2m_LwM2MStatusReport_DataEntry_DEFAULT NULL
#define lwm2m_LwM2MStatusReport_DataEntry_value_MSGTYPE lwm2m_LwM2MSensorValue

#define lwm2m_LwM2MSensorValue_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),   1) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),   2) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   5) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   6)
#define lwm2m_LwM2MSensorValue_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MSensorValue_DEFAULT NULL

#define lwm2m_LwM2MDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, aes_key,           4) \
X(a, CALLBACK, SINGULAR, BYTES,    mac_address,       5) \
X(a, STATIC,   SINGULAR, SINT32,   instance_id,       6) \
X(a, STATIC,   SINGULAR, BOOL,     banned,            7) \
X(a, STATIC,   SINGULAR, UENUM,    connection_type,   8)
#define lwm2m_LwM2MDevice_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDevice_DEFAULT NULL

#define lwm2m_LwM2MDeviceMap_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  devices,           1)
#define lwm2m_LwM2MDeviceMap_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceMap_DEFAULT NULL
#define lwm2m_LwM2MDeviceMap_devices_MSGTYPE lwm2m_LwM2MDeviceMap_DevicesEntry

#define lwm2m_LwM2MDeviceMap_DevicesEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define lwm2m_LwM2MDeviceMap_DevicesEntry_CALLBACK NULL
#define lwm2m_LwM2MDeviceMap_DevicesEntry_DEFAULT NULL
#define lwm2m_LwM2MDeviceMap_DevicesEntry_value_MSGTYPE lwm2m_LwM2MDevice

#define lwm2m_LwM2MDeviceChallenge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            1) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        2)
#define lwm2m_LwM2MDeviceChallenge_CALLBACK NULL
#define lwm2m_LwM2MDeviceChallenge_DEFAULT NULL

#define lwm2m_LwM2MDeviceChallengeAnswer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2)
#define lwm2m_LwM2MDeviceChallengeAnswer_CALLBACK NULL
#define lwm2m_LwM2MDeviceChallengeAnswer_DEFAULT NULL

#define lwm2m_LwM2MDeviceBootstrapRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   model,             1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            3) \
X(a, CALLBACK, SINGULAR, BYTES,    encrypted_data,    4)
#define lwm2m_LwM2MDeviceBootstrapRequest_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceBootstrapRequest_DEFAULT NULL

#define lwm2m_LwM2MBootstrapResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, STATIC,   SINGULAR, UINT32,   nounce,            2) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           3)
#define lwm2m_LwM2MBootstrapResponse_CALLBACK NULL
#define lwm2m_LwM2MBootstrapResponse_DEFAULT NULL

#define lwm2m_LwM2MDeviceBootstrap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               1) \
X(a, STATIC,   SINGULAR, UINT32,   instance_id,       2) \
X(a, CALLBACK, SINGULAR, BYTES,    admin_key,         3) \
X(a, CALLBACK, SINGULAR, BYTES,    aes_key,           4)
#define lwm2m_LwM2MDeviceBootstrap_CALLBACK pb_default_field_callback
#define lwm2m_LwM2MDeviceBootstrap_DEFAULT NULL

#define lwm2m_LwM2MResourceGet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   object_id,         1) \
X(a, STATIC,   SINGULAR, SINT32,   resource_id,       2) \
X(a, STATIC,   SINGULAR, SINT32,   resource_instance_id,   3) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),   4) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   7) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   8) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   9)
#define lwm2m_LwM2MResourceGet_CALLBACK NULL
#define lwm2m_LwM2MResourceGet_DEFAULT NULL

#define lwm2m_LwM2MResourceSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   object_id,         1) \
X(a, STATIC,   SINGULAR, SINT32,   resource_id,       2) \
X(a, STATIC,   SINGULAR, SINT32,   resource_instance_id,   3) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),   4) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   7) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   8) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   9)
#define lwm2m_LwM2MResourceSet_CALLBACK NULL
#define lwm2m_LwM2MResourceSet_DEFAULT NULL

#define lwm2m_FactoryPartition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   serial,            1) \
X(a, STATIC,   SINGULAR, SINT32,   pin,               2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, BYTES,    private_key,       4) \
X(a, STATIC,   SINGULAR, BYTES,    bootstrap_server,   5) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         6) \
X(a, STATIC,   SINGULAR, BYTES,    signature_cert,    7) \
X(a, STATIC,   SINGULAR, SINT32,   model,             8) \
X(a, STATIC,   SINGULAR, UINT32,   serial_number,     9)
#define lwm2m_FactoryPartition_CALLBACK NULL
#define lwm2m_FactoryPartition_DEFAULT NULL

#define lwm2m_Things_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   type,              1) \
X(a, STATIC,   SINGULAR, SINT32,   id,                2) \
X(a, CALLBACK, REPEATED, MESSAGE,  features,          3)
#define lwm2m_Things_CALLBACK pb_default_field_callback
#define lwm2m_Things_DEFAULT NULL
#define lwm2m_Things_features_MSGTYPE lwm2m_ThingsFeature

#define lwm2m_ThingsFeature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  data,            100)
#define lwm2m_ThingsFeature_CALLBACK pb_default_field_callback
#define lwm2m_ThingsFeature_DEFAULT NULL
#define lwm2m_ThingsFeature_data_MSGTYPE lwm2m_ThingsFeature_DataEntry

#define lwm2m_ThingsFeature_DataEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define lwm2m_ThingsFeature_DataEntry_CALLBACK NULL
#define lwm2m_ThingsFeature_DataEntry_DEFAULT NULL
#define lwm2m_ThingsFeature_DataEntry_value_MSGTYPE lwm2m_LwM2MSensorValue

#define lwm2m_ThingsTemplate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   type,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  features,          2)
#define lwm2m_ThingsTemplate_CALLBACK pb_default_field_callback
#define lwm2m_ThingsTemplate_DEFAULT NULL
#define lwm2m_ThingsTemplate_features_MSGTYPE lwm2m_ThingsTemplateFeature

#define lwm2m_ThingsTemplateFeature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  fields,            2)
#define lwm2m_ThingsTemplateFeature_CALLBACK pb_default_field_callback
#define lwm2m_ThingsTemplateFeature_DEFAULT NULL
#define lwm2m_ThingsTemplateFeature_fields_MSGTYPE lwm2m_ThingsTemplateField

#define lwm2m_ThingsTemplateField_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   type,              3)
#define lwm2m_ThingsTemplateField_CALLBACK pb_default_field_callback
#define lwm2m_ThingsTemplateField_DEFAULT NULL

#define lwm2m_ThingsTemplateAction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   type,              1) \
X(a, STATIC,   SINGULAR, SINT32,   id,                2) \
X(a, STATIC,   SINGULAR, SINT32,   feature_id,        3)
#define lwm2m_ThingsTemplateAction_CALLBACK NULL
#define lwm2m_ThingsTemplateAction_DEFAULT NULL

#define lwm2m_ThingsTemplateEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2)
#define lwm2m_ThingsTemplateEvent_CALLBACK pb_default_field_callback
#define lwm2m_ThingsTemplateEvent_DEFAULT NULL

extern const pb_msgdesc_t lwm2m_LwM2MMessage_msg;
extern const pb_msgdesc_t lwm2m_LwM2MCommand_msg;
extern const pb_msgdesc_t lwm2m_LwM2MStatusReport_msg;
extern const pb_msgdesc_t lwm2m_LwM2MStatusReport_DataEntry_msg;
extern const pb_msgdesc_t lwm2m_LwM2MSensorValue_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDevice_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceMap_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceMap_DevicesEntry_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceChallenge_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceChallengeAnswer_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceBootstrapRequest_msg;
extern const pb_msgdesc_t lwm2m_LwM2MBootstrapResponse_msg;
extern const pb_msgdesc_t lwm2m_LwM2MDeviceBootstrap_msg;
extern const pb_msgdesc_t lwm2m_LwM2MResourceGet_msg;
extern const pb_msgdesc_t lwm2m_LwM2MResourceSet_msg;
extern const pb_msgdesc_t lwm2m_FactoryPartition_msg;
extern const pb_msgdesc_t lwm2m_Things_msg;
extern const pb_msgdesc_t lwm2m_ThingsFeature_msg;
extern const pb_msgdesc_t lwm2m_ThingsFeature_DataEntry_msg;
extern const pb_msgdesc_t lwm2m_ThingsTemplate_msg;
extern const pb_msgdesc_t lwm2m_ThingsTemplateFeature_msg;
extern const pb_msgdesc_t lwm2m_ThingsTemplateField_msg;
extern const pb_msgdesc_t lwm2m_ThingsTemplateAction_msg;
extern const pb_msgdesc_t lwm2m_ThingsTemplateEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lwm2m_LwM2MMessage_fields &lwm2m_LwM2MMessage_msg
#define lwm2m_LwM2MCommand_fields &lwm2m_LwM2MCommand_msg
#define lwm2m_LwM2MStatusReport_fields &lwm2m_LwM2MStatusReport_msg
#define lwm2m_LwM2MStatusReport_DataEntry_fields &lwm2m_LwM2MStatusReport_DataEntry_msg
#define lwm2m_LwM2MSensorValue_fields &lwm2m_LwM2MSensorValue_msg
#define lwm2m_LwM2MDevice_fields &lwm2m_LwM2MDevice_msg
#define lwm2m_LwM2MDeviceMap_fields &lwm2m_LwM2MDeviceMap_msg
#define lwm2m_LwM2MDeviceMap_DevicesEntry_fields &lwm2m_LwM2MDeviceMap_DevicesEntry_msg
#define lwm2m_LwM2MDeviceChallenge_fields &lwm2m_LwM2MDeviceChallenge_msg
#define lwm2m_LwM2MDeviceChallengeAnswer_fields &lwm2m_LwM2MDeviceChallengeAnswer_msg
#define lwm2m_LwM2MDeviceBootstrapRequest_fields &lwm2m_LwM2MDeviceBootstrapRequest_msg
#define lwm2m_LwM2MBootstrapResponse_fields &lwm2m_LwM2MBootstrapResponse_msg
#define lwm2m_LwM2MDeviceBootstrap_fields &lwm2m_LwM2MDeviceBootstrap_msg
#define lwm2m_LwM2MResourceGet_fields &lwm2m_LwM2MResourceGet_msg
#define lwm2m_LwM2MResourceSet_fields &lwm2m_LwM2MResourceSet_msg
#define lwm2m_FactoryPartition_fields &lwm2m_FactoryPartition_msg
#define lwm2m_Things_fields &lwm2m_Things_msg
#define lwm2m_ThingsFeature_fields &lwm2m_ThingsFeature_msg
#define lwm2m_ThingsFeature_DataEntry_fields &lwm2m_ThingsFeature_DataEntry_msg
#define lwm2m_ThingsTemplate_fields &lwm2m_ThingsTemplate_msg
#define lwm2m_ThingsTemplateFeature_fields &lwm2m_ThingsTemplateFeature_msg
#define lwm2m_ThingsTemplateField_fields &lwm2m_ThingsTemplateField_msg
#define lwm2m_ThingsTemplateAction_fields &lwm2m_ThingsTemplateAction_msg
#define lwm2m_ThingsTemplateEvent_fields &lwm2m_ThingsTemplateEvent_msg

/* Maximum encoded size of messages (where known) */
/* lwm2m_LwM2MMessage_size depends on runtime parameters */
/* lwm2m_LwM2MStatusReport_size depends on runtime parameters */
/* lwm2m_LwM2MStatusReport_DataEntry_size depends on runtime parameters */
/* lwm2m_LwM2MSensorValue_size depends on runtime parameters */
/* lwm2m_LwM2MDevice_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceMap_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceMap_DevicesEntry_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceBootstrapRequest_size depends on runtime parameters */
/* lwm2m_LwM2MDeviceBootstrap_size depends on runtime parameters */
/* lwm2m_Things_size depends on runtime parameters */
/* lwm2m_ThingsFeature_size depends on runtime parameters */
/* lwm2m_ThingsFeature_DataEntry_size depends on runtime parameters */
/* lwm2m_ThingsTemplate_size depends on runtime parameters */
/* lwm2m_ThingsTemplateFeature_size depends on runtime parameters */
/* lwm2m_ThingsTemplateField_size depends on runtime parameters */
/* lwm2m_ThingsTemplateEvent_size depends on runtime parameters */
#define LWM2M_LWM2M_PB_H_MAX_SIZE                lwm2m_LwM2MBootstrapResponse_size
#define lwm2m_FactoryPartition_size              334
#define lwm2m_LwM2MBootstrapResponse_size        523
#define lwm2m_LwM2MCommand_size                  2
#define lwm2m_LwM2MDeviceChallengeAnswer_size    165
#define lwm2m_LwM2MDeviceChallenge_size          40
#define lwm2m_LwM2MResourceGet_size              277
#define lwm2m_LwM2MResourceSet_size              277
#define lwm2m_ThingsTemplateAction_size          18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
