/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "lwm2m.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lwm2m_LwM2MMessage, lwm2m_LwM2MMessage, 2)


PB_BIND(lwm2m_LwM2MAppearance, lwm2m_LwM2MAppearance, AUTO)


PB_BIND(lwm2m_LwM2MDevice, lwm2m_LwM2MDevice, AUTO)


PB_BIND(lwm2m_LwM2MDeviceMap, lwm2m_LwM2MDeviceMap, AUTO)


PB_BIND(lwm2m_LwM2MDeviceMap_DevicesEntry, lwm2m_LwM2MDeviceMap_DevicesEntry, AUTO)


PB_BIND(lwm2m_LwM2MDeviceChallenge, lwm2m_LwM2MDeviceChallenge, AUTO)


PB_BIND(lwm2m_LwM2MDeviceChallengeAnswer, lwm2m_LwM2MDeviceChallengeAnswer, AUTO)


PB_BIND(lwm2m_LwM2MBootstrapResponse, lwm2m_LwM2MBootstrapResponse, AUTO)


PB_BIND(lwm2m_LwM2MResourceGet, lwm2m_LwM2MResourceGet, AUTO)


PB_BIND(lwm2m_LwM2MResourceSet, lwm2m_LwM2MResourceSet, AUTO)


PB_BIND(lwm2m_LwM2MBootstrapMessage, lwm2m_LwM2MBootstrapMessage, AUTO)


PB_BIND(lwm2m_FactoryPartition, lwm2m_FactoryPartition, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

